name: MinetopiaFarms
version: ${project.version}
api-version: 1.13
author: MrWouter
description: 'MinetopiaFarms is een gemakkelijke manier om beroepen aan jouw server toe te voegen!'
main: nl.mrwouter.minetopiafarms.Main
depend: [WorldEdit, WorldGuard, Vault, MinetopiaSDB]
softdepend: [Citizens]
commands:
     kies:
     minetopiafarms:
        aliases: [mtfarms, farms]